name: mooncake_leaderboard
description: An absolute bare-bones web app.
version: 0.1.1+01100
homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  equatable:
  graphql: 2.1.0
  json_annotation:
  meta:
  path:

dev_dependencies:
  build_runner:
  build_web_compilers:
  json_serializable:
  pedantic:
  sass_builder:
